version: "3"


services:
  backend:
    container_name: processor_backend
    image: processor-backend:latest
    build: ./backend
    environment:
      - NODE_ENV="PROD"
    ports:
      - "3000:3000"

  frontend:
    container_name: processor_frontend
    build: ./frontend
    image: processor-frontend:latest
    ports:
      - "80:80"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27017"
