const cron = require('node-cron');
import { NodeManager } from "../node-manager";

import { BaseNode } from "../base-node";
import chalk from "chalk";


const NODE_TYPE = "CRON"

const requiredOptions = ["CronExpression"];

export class CronNode extends BaseNode{
    cronExpression: string;
    task: any;


    constructor(name: string, id: string, options: any, targetsSuccess: any) {
        super(name, NODE_TYPE, id, targetsSuccess, []);
        this.validateOptions(options);
        this.cronExpression = this.getCronExpressionFromOptions("CronExpression", options);
        this.task = this.createTask();
        this.startTask();
        NodeManager.addNode(this);
    }

    createTask() {
        return cron.schedule(this.cronExpression, () =>  {
            this.onSuccess(`Payload ${new Date()}`);
        }, {
            scheduled: false
        });
    }

    changeTask(newCronExpression: string) {
        console.log(`Changing CRON to: ${newCronExpression}`)
        if (cron.validate(newCronExpression)) {
            console.log("Valid")
        } else {
            console.log("Invalid")
        }
        this.task.destroy();
        this.cronExpression = newCronExpression;
        this.task = this.createTask();
        this.startTask();
    }

    startTask() {
        this.task.start();
    }

    stop() {
        console.log("Cron Task Stopped")
        this.task.stop();
    }

    /**
     * Options are generated by the frontend end therefore a source for errors.
     * This method checks the passed options of the constructor against the requiredOptions of this class.
     * @param options Passed options
     */
    validateOptions(options: any) {
        requiredOptions.forEach(option => {
            let cronExpression = options[option];
            if (!cronExpression) throw new Error(`${chalk.red(NODE_TYPE)}: Option '${option}' is not present`);
        });
    }

    /**
     * Extracts the optionValue for optionName
     * @param options 
     */
    getCronExpressionFromOptions(optionName: string, options: any) {
        return options[optionName];
    }
}